name: cd-release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build prod
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v3

      # OIDC
      - name: GitHub Actions OIDC to AWS Roles
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ASSUME_ROLE_PROD }}
          role-session-name: github-visitor-lambda-session

      # Terraform remote backend state
      - name: Terraform S3 Backend
        id: create
        run: aws s3api create-bucket --bucket ${{ secrets.KEY_S3_TF_PROD }} --region ${{ vars.REGION }} --create-bucket-configuration LocationConstraint=${{ vars.REGION }}
        continue-on-error: true

      # Terraform
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config='bucket=${{ secrets.S3_TF_PROD }}' \
            -backend-config='key=${{ secrets.KEY_S3_TF_PROD }}' \
            -backend-config='region=${{ vars.REGION }}'

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: ${{ github.event_name == 'push' }}
        run: |
          terraform plan \
            -var='project_name=${{ vars.VISITOR_LAMBDA_NAME_PROD }}' \
            -var='region=${{ vars.REGION }}' \
            -var='stage=${{ vars.API_GATEWAY_STAGE_PROD }}' \
            -var='origin=${{ vars.ORIGIN_PROD }}' \
            -var='api_resource_name=${{ vars.API_RESOURCE_NAME }}' \
            -var='db_name=${{ vars.DB_NAME_PROD }}' \
            -refresh=false  -no-color -out=plan.out
        continue-on-error: false

      - name: Terraform Plan Status
        if: ${{ steps.plan.outcome == 'failure' }}
        run: exit 1

      - name: Terraform Apply
        id: apply
        if: ${{ github.event_name == 'push' }}
        run: |
          terraform apply plan.out
          API_URL=$(terraform output -raw visitor2_stage)
          echo "CYPRESS_API_URL=${API_URL}" >> $GITHUB_ENV
        continue-on-error: true

      - name: Terraform Apply Status
        if: ${{ steps.apply.outcome == 'failure' }}
        run: exit 1

      # cypress
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v5
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots


